USE WORLD;
DESC CITY;
DESC COUNTRY;
DESC COUNTRYLANGUAGE;
SHOW databases;
SHOW tables;
SELECT* FROM CITY;
SELECT NAME 
FROM COUNTRY;
SELECT HEADOFSTATE FROM COUNTRY;
SELECT CODE, NAME FROM COUNTRY WHERE CODE='KOR';
SELECT * FROM COUNTRY;
SELECT * FROM COUNTRY WHERE POPULATION >= 10000000;

SELECT CO.NAME 나라이름, CI.NAME 도시이름
FROM COUNTRY CO INNER JOIN CITY CI
ON CO.CODE = CI.COUNTRYCODE
ORDER BY 나라이름 DESC;

SELECT NAME, POPULATION
FROM COUNTRY
ORDER BY POPULATION desc;
SELECT *
FROM COUNTRYLANGUAGE
WHERE COUNTRYCODE = 'KOR'
ORDER BY PERCENTAGE; #조회
       
UPDATE COUNTRYLANGUAGE
SET LANGUAGE = 'Japanese'
WHERE COUNTRYCODE = 'KOR' AND LANGUAGE = 'Chinese'; #중국어를 일본어로 바꾸기

UPDATE COUNTRYLANGUAGE
SET LANGUAGE = 'Chinese'
WHERE COUNTRYCODE = 'KOR' AND LANGUAGE = 'Japanese'; #일본어를 중국어로 바꾸기

SELECT ID, NAME, (SELECT COUNTRYCODE FROM CITY B WHERE A.ID = B.ID AND POPULATION >= 100000) 나라코드 
FROM CITY A;

SELECT ID, NAME, COUNTRYCODE 나라코드 
FROM CITY A;

SELECT CODE 국가코드, NAME 나라이름, INDEPYEAR 독립년도
FROM COUNTRY
WHERE INDEPYEAR IS NULL
ORDER BY NAME;

SELECT C.INDEPYEAR
FROM (SELECT * FROM COUNTRY WHERE INDEPYEAR >= 1990) C
ORDER BY C.INDEPYEAR DESC;

SELECT * FROM DUAL;

SELECT CONTINENT, NAME, POPULATION
FROM COUNTRY
WHERE POPULATION >100000; #BETWEEN 10000 AND 100000;

SELECT NAME, POPULATION
FROM COUNTRY
WHERE CAPITAL IS NULL;

SELECT INDEPYEAR 독립년도, COUNT(*) 갯수
FROM COUNTRY
WHERE INDEPYEAR > 1990
GROUP BY INDEPYEAR;

SELECT CONTINENT 대륙, NAME 나라, POPULATION "인구 수", GNP 국내총생산
FROM COUNTRY
WHERE POPULATION>10000000 AND GNP < 100000
ORDER BY 3 DESC, 4 DESC;

SELECT CONTINENT 대륙, NAME 나라, POPULATION "인구 수", GNP 국내총생산
FROM COUNTRY
WHERE CONTINENT NOT IN('ASIA', 'AFRICA') AND POPULATION>10000000 AND GNP < 100000
ORDER BY 3 DESC, 4 DESC;




